accounts/urls.py
from django.urls import path
from .views import UserProfile,register
from django.contrib.auth.views import login,logout
app_name="accounts"
urlpatterns = [
    path('login/', login,{'template_name':'accounts/login.html','extra_context':{'login':True}},name="login"),
    path('register/',register,name="register"),
    path('logout/', logout,{'next_page':'home:index'},name="logout"),
    path('profile/<username>', UserProfile.as_view(),name="profile"),
]

forum/urls.py
from django.urls import path,re_path
from .views import ForumIndexView,ForumSearchView,ListPostsView,ForumExploreView,ForumSectionDetailView,PostCreateView,PostsUpdateView,Subscribe,Unsubscribe,PostsView
app_name="forum"
urlpatterns = [
    path('',ForumIndexView.as_view(),name="index"),
    path('explore/',ForumExploreView.as_view(),name="explore"),
    path('search/',ForumSearchView.as_view(),name="search"),
    re_path(r'^sections/(?P<section_link>[\w-]+)/$',ForumSectionDetailView.as_view(),name="sections"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('subscribe/<int:pk>', Subscribe.as_view(), name="subscribe"),
    path('unsubscribe/<int:pk>', Unsubscribe.as_view(), name="unsubscribe"),
    path('posts/', ListPostsView.as_view(), name="posts_general"),
    path('posts/<int:pk>', PostsView.as_view(), name="posts"),
    path('posts/edit/<int:pk>', PostsUpdateView.as_view(), name="edit_post"),
]

growithme/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('forum/',include('forum.urls')),
    path('minefield/',include('minefield.urls')),
]

home/urls.py
from django.urls import path
from . import views
app_name="home"
urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.urls import reverse

class ForumSection(models.Model):
    name=models.CharField(max_length=75)
    section_desc=models.TextField(blank=True,null=True)
    admin=models.ForeignKey(User,on_delete=models.CASCADE,default=1,related_name="ForumSection_admin")
    picture_link=models.CharField(max_length=250,default="default_section.png")
    section_link = models.SlugField(null=True, blank=True)
    subscribers=models.ManyToManyField(User,related_name="ForumSection_subscribers")
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("forum:sections",kwargs={'section_link':self.section_link})
    @property
    def title(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=250)
    author=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    section=models.ForeignKey(ForumSection,on_delete=models.CASCADE)
    content=models.TextField()
    subject=models.CharField(max_length=150,null=True,blank=True)
    created_time=models.DateTimeField(auto_now_add=True)
    updated_time=models.DateTimeField(auto_now=True)
    upvote=models.ManyToManyField(User,blank=True,related_name="like")
    downvote=models.ManyToManyField(User,blank=True,related_name="dislike")
    def __str__(self):
        return self.title
    class Meta:
        ordering=['-updated_time','-created_time']

class Comment(models.Model):
    commentor=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    content=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.content
    class Meta:
        ordering=['-created_time']

def forum_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.section_link:
        instance.section_link=unique_slug_generator(instance)
pre_save.connect(forum_pre_save_receiver,sender=ForumSection)

forum/forms.py
from django import forms
from .models import Post,ForumSection

class PostCreationForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','section','subject','content']

    def __init__(self, *args, **kwargs):
        super(PostCreationForm, self).__init__(*args, **kwargs)
        self.fields['section'].widget.attrs['class'] = 'form-control'
        self.fields['content'].widget.attrs['class'] = 'form-control'
        self.fields['subject'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['class'] = 'form-control'

forum/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, View,UpdateView
from django.contrib.auth.models import User
from .forms import PostCreationForm
from .models import ForumSection, Post


class ForumIndexView(LoginRequiredMixin,TemplateView):
    login_url = "/accounts/login/"
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({'forum': True, 'logged_in': True})
        return context
    template_name = "forum/forum.html"

class ForumSearchView(LoginRequiredMixin,TemplateView):
    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context.update({'forum': True, 'logged_in': True})
        return context
    template_name = "forum/forum_search.html"

class ForumExploreView(LoginRequiredMixin,ListView):
    def get_queryset(self):
        object_list = ForumSection.objects.all()
        return object_list

    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context.update({'forum':True,'logged_in':True,'explore':True})
        return context
    template_name = "forum/forum_explore.html"


class ForumSectionDetailView(LoginRequiredMixin,DetailView):
    def get_object(self):
        section_link=self.kwargs.get("section_link")
        obj=get_object_or_404(ForumSection,section_link=section_link)
        return obj
    def get_context_data(self, *args,**kwargs):
        section_link = self.kwargs.get("section_link")
        obj = get_object_or_404(ForumSection, section_link=section_link)
        subscribers = list(obj.subscribers.all())
        is_subscribed= self.request.user in subscribers
        context = super().get_context_data(*args,**kwargs)
        context.update({'forum': True, 'logged_in': True, 'explore': True ,'is_subscribed':is_subscribed})
        return context
    template_name = "forum/forum_detail.html"

class PostCreateView(LoginRequiredMixin,CreateView):
    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context.update({'forum':True,'logged_in':True,'explore':True})
        return context
    form_class = PostCreationForm
    template_name = "forum/post_create.html"
    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = User.objects.get(id=self.request.user.pk)
        post.save()
        return redirect(reverse('forum:posts',kwargs={'pk':post.id}))

class Subscribe(LoginRequiredMixin,View):
    def get(self,request,*args,**kwargs):
        section_pk=kwargs['pk']
        loggedin_user=self.request.user
        section = get_object_or_404(ForumSection, id=section_pk)
        subscribers = list(section.subscribers.all())
        is_subscribed = self.request.user in subscribers
        if section and not is_subscribed :
            section.subscribers.add(loggedin_user)
        return redirect('forum:sections',section_link=section.section_link)

class Unsubscribe(LoginRequiredMixin,View):
    def get(self,request,*args,**kwargs):
        section_pk=kwargs['pk']
        loggedin_user=self.request.user
        section = get_object_or_404(ForumSection, id=section_pk)
        subscribers = list(section.subscribers.all())
        is_subscribed = self.request.user in subscribers
        if section and is_subscribed :
            section.subscribers.remove(loggedin_user)
        return redirect('forum:sections',section_link=section.section_link)

class PostsUpdateView(LoginRequiredMixin,UpdateView):
    '''def get_object(self):
        post_no=self.kwargs.get("pk")
        obj=get_object_or_404(Post,pk=post_no)
        return obj'''
    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context.update({'forum': True, 'logged_in': True, 'explore': True,'user':self.request.user.pk})
        return context
    model = Post
    fields = ['title','section','content']
    def get_template_names(self):
        if self.request.user.pk == get_object_or_404(Post,pk=self.kwargs.get("pk")).author.pk:
            template_name="forum/post_update.html"
            return template_name
        else:
            print(self.kwargs.get("pk"))
            return redirect('forum:posts', pk=self.kwargs.get("pk"))


class PostsView(LoginRequiredMixin,DetailView):
    def get_object(self):
        post_no=self.kwargs.get("pk")
        obj=get_object_or_404(Post,pk=post_no)
        return obj
    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context.update({'forum': True, 'logged_in': True, 'explore': True,'user':self.request.user.pk})
        return context
    model = Post
    fields = ['title','section','content']
    template_name="forum/post_detail.html"

class ListPostsView(ListView):
    pass

forum/templates/forum/forum.html
{% extends 'home/includes/base1.html' %}
{% block content1 %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/home/css/meny.css' %}" />
    <link rel="stylesheet" href="{% static '/forum/css/forum_main.css' %}" />
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

{% endblock content1 %}
{% block head_title %}Forum{% endblock %}
{% block body %}
    {% include 'home/includes/navbar.html' %}
    <div class="contents">
        <section class="intro">
                <div class="intro-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 col-md-offset-2 introstuff">
                                <h1 class="forum-heading">Forum</h1>
                                <p class="intro-text">An online repository and a discussion group for jargon talks along Q/A Threads</p>
                                    <div class="btn-group btn-group-justified">
                                        <a class="btn btn-info btn-lg" href="{% url 'forum:explore' %}"><svg class="icon icon-binoculars"><use xlink:href="#icon-binoculars"></use></svg>&nbsp;Explore</a>
                                        <a class="btn btn-danger btn-lg" href="{% url 'forum:create' %}"><svg class="icon icon-quill"><use xlink:href="#icon-quill"></use></svg>&nbsp;Create</a>
                                        <a class="btn btn-lg btn-success" href="{% url 'forum:search' %}"><svg class="icon icon-search"><use xlink:href="#icon-search"></use></svg>&nbsp;Search</a>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
        </section>
    </div>
    {% block additional %}
    {% load static %}
    <script src="{% static "/forum/js/grayscale.js" %}"></script>
    {% endblock additional %}

{% endblock body %}

forum/templates/forum/forum_detail.html
{% extends 'home/includes/base1.html' %}
{% block content1 %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/home/css/meny.css' %}" />
    <link rel="stylesheet" href="{% static '/forum/css/forum_main.css' %}" />

{% endblock content1 %}
{% block head_title %}{{ object.name }}&nbsp;Forum{% endblock %}
{% block body %}
    {% include 'home/includes/navbar.html' %}
    <div class="contents">
        <div class="container">
            <h1 class="modal-header">Forum</h1>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'forum:index' %}">Forum</a></li>
                <li class="breadcrumb-item"><a href="{% url 'forum:explore' %}">Sections</a></li>
                <li class="breadcrumb-item active">{{ object.name }}</li>
              </ol>
            </nav>



            <div class="container">
                <div class="jumbotron clearfix">
                    <header><h1>{{ object.name }}</h1></header>
                    {% if object.section_desc %}<div class="card mb-1"><p class="card-body">{{ object.section_desc }}</p></div>{% endif %}
                    <div class="row">
                    <div class="col-xl-5 col-lg-5 col-md-12 section_desc">
                                <div class="card">
                                    <span class="admin card-header text-capitalize text-center">Admin : {{ object.admin }}</span>
                                </div>
                                <div class="card container-fluid">
                                    {% if not object.subscribers.all.count %}<div class="card-header text-center">Subscribers : <span class="badge-success p-1">{{ object.subscribers.all.count }}</span></div>
                                    {% else %}
                                        <a href="#" class="subs_toggle" data-toggle="modal" data-target="#subs"><div class="card-header text-center">Subscribers : <span class="badge-success p-1">{{ object.subscribers.all.count }}</span></div></a>
                                    {% endif %}
                                </div>
                        <div class="card text-center"><div class="card-header">Posts : {{ object.post_set.all.count }}</div></div>
                        <div class="text-center buttons_fdetail">
                            <a href="{% url 'forum:create' %}" class="btn btn-info mt-1">Add a Post/Question</a>
                            {% if not is_subscribed %}
                            <a href="{% url 'forum:subscribe' pk=object.pk %}" class="btn btn-success mt-1">
                                <svg class="icon icon-plus"><use xlink:href="#icon-plus"></use></svg>&nbsp;Subscribe
                            </a>
                            {% else %}
                                <a href="{% url 'forum:unsubscribe' pk=object.pk %}" class="btn btn-success mt-1 subscribe-d" id="subscribed" style="width:123px;height:38px">
                                <svg class="icon icon-checkmark"><use xlink:href="#icon-checkmark"></use></svg>&nbsp;Subscribed
                                </a>
                            {% endif %}
                        </div>
                    </div>
                        <div class="col-xl-6 col-lg-6 col-md-12"><img src="{% load static %}{% static 'forum/images/'|add:object.picture_link %}" class="img-thumbnail"/></div>
                </div>
                </div>
    </div

      <div class="container mb-4">
          <h1 class="header">POSTS</h1>
        {% if not object.post_set.all %}
            This Section has no posts yet ! Be the First One To Post !
        {% endif %}
      <div class="row">
          {% for post in object.post_set.all %}
            <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
            <span class="dot"></span>
            <a href="{% url 'forum:posts' pk=post.pk %}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
                {% if post.subject %}
              <h3 class="post-subtitle">
                <code class="float-left">></code>
                {{ post.subject }}
              </h3>
                {% endif %}
                <h6 class="post-contents">
                {{ post.content|linebreaks|truncatewords:10 }}
              </h6>
            </a>
            <p class="post-meta">Posted by
              <a href="{% url 'accounts:profile' username=post.author.username %}">{{ post.author }}</a>
              , {{ post.created_time|timesince}} ago </p>
          </div>
          <hr>

          </div>
            <hr>
        {% endfor %}
        </div>
      </div>
    </div>


    </div>
    </div>




    {% if object.subscribers.all %}
        <div class="modal fade" id="subs" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="subs-title">Subscribers</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <ul class="card">
                        {% for subs in object.subscribers.all %}
                            <a><li class="card-body">{{ subs.username }}</li></a>
                        {% endfor %}
                    </ul>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
    {% endif %}
        <script src="{% load static %}{% static "forum/js/forum.js" %}" type="text/javascript"></script>
{% endblock body %}

forum/templates/forum/forum_explore.html
{% extends 'home/includes/base1.html' %}
{% block content1 %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/home/css/meny.css' %}" />
    <link rel="stylesheet" href="{% static '/forum/css/forum_main.css' %}" />

{% endblock content1 %}
{% block head_title %}Forum{% endblock %}
{% block body %}
    {% include 'home/includes/navbar.html' %}
    <div class="contents">
        <div class="container">
        <h1 class="modal-header">Forum</h1>
            <ul class="explore_ul">
                <div class="row">
                        {% for object in object_list %}
                            <li class="list-group-item col-sm-12 col-xl-4 col-lg-4 col-md-6 section_{{ object.pk }}">
                                   <a href="{{ object.get_absolute_url }}" class="explore_a">
                                        <img src="{% load static %}{% static 'forum/images/'|add:object.picture_link %}" class="img-thumbnail explore_img"/>
                                       <br/><span class="title">{{ object.name }}</span>
                                   </a>
                            </li>
                        {% endfor %}
                </div>
            </ul>
            </div>
    </div>

{% endblock body %}

forum/templates/forum/forum_not_logged.html
{% extends 'home/includes/base1.html' %}
{% block content1 %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/home/css/meny.css' %}" />
    <link rel="stylesheet" href="{% static '/forum/css/forum_main.css' %}" />
{% endblock content1 %}
{% block head_title %}Forum{% endblock %}
{% block body %}
    {% include 'home/includes/navbar.html' %}
        <div class="contents">
            <div class="peculiar_forum">
                {% load static %}
                <img class="rick_svg"src="{% static 'forum/images/rick1.svg' %}"/>
                <div class="login_required_text">
                    <h1>You Have To Be Logged In To Use This Feature !</h1>
                </div>
                <div class="login_redirect_text">
                    {% load static %}<center><a href="{% url 'accounts:login' %}" class="login_a"><svg class="icon icon-key login_a_svg" style="width: 20px;height:20px;"><use xlink:href="#icon-key"></use></svg>&nbsp;Login</a>
                    <a href="{% url 'accounts:register' %}" class="register_a"><svg class="icon icon-clipboard register_a_svg" style="width: 20px;height:20px;"><use xlink:href="#icon-clipboard"></use></svg>&nbsp;Sign Up</a></center>
                </div>
            </div>
        </div>


{% endblock %}

forum/templates/forum/forum_search.html
{% extends 'home/includes/base1.html' %}
{% block content1 %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/home/css/meny.css' %}" />
    <link rel="stylesheet" href="{% static '/forum/css/forum_main.css' %}" />
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

{% endblock content1 %}
{% block head_title %}Forum{% endblock %}
{% block body %}
    {% include 'home/includes/navbar.html' %}
    <div class="contents">
        <section class="intro">
                <div class="intro-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 col-md-offset-2 introstuff">
                                <h1 class="forum-heading">Forum</h1>
                                <p class="intro-text">An online repository and a discussion group for jargon talks along Q/A Threads</p>
                                <form method="get" action="{%  url 'forum:search'%}" class="search_group">
                                    <div class="input-group">
                                        <input type="text" class="input-group input-group-text search_input" name="keyword"placeholder="Enter Keywords Here"/>
                                        <button class="btn btn-lg btn-success search_button" type="submit">
                                            <svg class="icon icon-search"><use xlink:href="#icon-search"></use></svg>
                                            <span class="hide_text_sm">Search</span>
                                        </button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
        </section>
    </div>
    {% block additional %}
    {% load static %}
    <script src="{% static "/forum/js/grayscale.js" %}"></script>
    {% endblock additional %}

{% endblock body %}

forum/templates/forum/post_create.html
{% extends 'home/includes/base1.html' %}
{% block content1 %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/forum/css/forum_main.css' %}" />
    <link rel="stylesheet" href="{% static '/home/css/meny.css' %}" />
{% endblock content1 %}
{% block head_title %}Create | Forum{% endblock %}

{% block body %}
    {% include 'home/includes/navbar.html' %}
    <div class="contents">
    <div class="container">
            <div class="PostBox">
                <h1 class="modal-header">Forum</h1>
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'forum:index' %}">Forum</a></li>
                    <li class="breadcrumb-item active">Create</li>
                  </ol>
                </nav>
                            <h2 class="modal-header"><svg class="icon icon-quill" style="color:#000;"><use xlink:href="#icon-quill"></use></svg>Create Post / Question</h2>
                <form method="post" class="form-control">
                    {% csrf_token %}
                    <div class="post_form">
                        {{ form.as_p}}
                        <input type="submit" name="submit" value="Submit" class="btn btn-info"/>
                        </div>
                    </form>
            </div>

    </div>
    </div>
    <script src="{% load static %}{% static "forum/js/forum.js" %}" type="text/javascript"></script>
{% endblock %}

forum/templates/forum/post_detail.html
{% extends 'home/includes/base1.html' %}
{% block content1 %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/home/css/meny.css' %}" />
    <link rel="stylesheet" href="{% static '/forum/css/forum_main.css' %}" />

{% endblock content1 %}
{% block head_title %}{{ object.name }}&nbsp;Forum{% endblock %}
{% block body %}
    {% include 'home/includes/navbar.html' %}
    <div class="contents">
        <div class="container">
            <h1 class="modal-header">Forum</h1>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'forum:index' %}">Forum</a></li>
                <li class="breadcrumb-item"><a href="{% url 'forum:posts_general' %}">Posts</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'forum:sections' section_link=object.section.section_link %}">{{ object.section.name }}</a></li>
                <li class="breadcrumb-item active">{{ object.title }}</li>
              </ol>
            </nav>

                <div class="container">
                <div class="clearfix">
                     <span class="admin text-center btn badge-info">By : <a href="{% url 'accounts:profile' username=object.author.username%}" class="user_url">{{ object.author }}</a></span>
                <hr/>
                    <header><h2 class="post-title">{{ object.title }}</h2></header>
                    {% if object.subject %}<header><h5 class="post-subtitle">{{ object.subject }}</h5></header>{% endif %}
                    <div class="section badge badge-primary"><span class="dot" style="background-color:#fff;width:9px;height:9px;"></span>&nbsp;{{ object.section }}</div>
                    <hr>
                    <div class="post-contents">
                        {{ object.content|linebreaks }}
                    </div>
                </div>
            </div>

                </div>
            </div>
        <script src="{% load static %}{% static "forum/js/forum.js" %}" type="text/javascript"></script>
{% endblock body %}

forum/templates/forum/post_update.html
{% extends 'home/includes/base1.html' %}
{% block content1 %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/home/css/meny.css' %}" />
    <link rel="stylesheet" href="{% static '/forum/css/forum_main.css' %}" />

{% endblock content1 %}
{% block head_title %}{{ object.name }}&nbsp;Forum{% endblock %}
{% block body %}
    {% include 'home/includes/navbar.html' %}
    <div class="contents">
        <div class="container">
            <h1 class="modal-header">Forum</h1>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'forum:index' %}">Forum</a></li>
                <li class="breadcrumb-item"><a href="{% url 'forum:posts_general' %}">Posts</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'forum:sections' section_link=object.section.section_link %}">{{ object.section.name }}</a></li>
                <li class="breadcrumb-item active">{{ object.title }}</li>
              </ol>
            </nav>
            {% if user != object.author.pk %}
            <div class="container">
                <div class="jumbotron clearfix">
                    <header><h1>{{ object.title }}</h1></header>
                    <div class="row">
                    <div class="col-xl-5 col-lg-5 col-md-12 section_desc">
                                <div class="card">
                                    <span class="admin card-header text-capitalize text-center">Author : {{ object.author }}</span>
                                </div>
                        <div class="card">
                                    <span class="admin card-header text-capitalize text-center">Date Created : {{ object.created_time }}</span>
                                </div>
                        <div class="card">
                            <div class="card card-header">Section :</div>
                            <div class="card card-body">{{ object.section }}</div>
                        </div>
                        <div class="card">
                            <div class="card card-header">Content :</div>
                            <div class="card card-body">{{ object.content }}</div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
            {% else %}
                <h2 class="modal-header"><svg class="icon icon-quill" style="color:#000;"><use xlink:href="#icon-quill"></use></svg>Edit Post / Question</h2>
                <form method="post" class="form-control">
                    {% csrf_token %}
                    <div class="post_form">
                        {{ form.as_p}}
                        <input type="submit" name="submit" value="Submit" class="btn btn-info"/>
                        </div>
                    </form>
            {% endif %}
                </div>
            </div>
        <script src="{% load static %}{% static "forum/js/forum.js" %}" type="text/javascript"></script>
{% endblock body %}