accounts/urls.py
from django.urls import path
from .views import UserProfile,register
from django.contrib.auth.views import login,logout
app_name="accounts"
urlpatterns = [
    path('login/', login,{'template_name':'accounts/login.html','extra_context':{'login':True}},name="login"),
    path('register/',register,name="register"),
    path('logout/', logout,{'next_page':'home:index'},name="logout"),
    path('profile/<username>', UserProfile.as_view(),name="profile"),
]

forum/urls.py
from django.urls import path,re_path
from .views import ForumIndexView,ForumSearchView,ListPostsView,ForumExploreView,ForumSectionDetailView,PostCreateView,PostsUpdateView,Subscribe,Unsubscribe,PostsView
app_name="forum"
urlpatterns = [
    path('',ForumIndexView.as_view(),name="index"),
    path('explore/',ForumExploreView.as_view(),name="explore"),
    path('search/',ForumSearchView.as_view(),name="search"),
    re_path(r'^sections/(?P<section_link>[\w-]+)/$',ForumSectionDetailView.as_view(),name="sections"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('subscribe/<int:pk>', Subscribe.as_view(), name="subscribe"),
    path('unsubscribe/<int:pk>', Unsubscribe.as_view(), name="unsubscribe"),
    path('posts/', ListPostsView.as_view(), name="posts_general"),
    path('posts/<int:pk>', PostsView.as_view(), name="posts"),
    path('posts/edit/<int:pk>', PostsUpdateView.as_view(), name="edit_post"),
]

growithme/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('forum/',include('forum.urls')),
    path('minefield/',include('minefield.urls')),
]

home/urls.py
from django.urls import path
from . import views
app_name="home"
urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
]

minefield/urls.py
from django.urls import path
from . import views
app_name="minefield"
urlpatterns = [
    path('',views.index,name='index'),
]

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
def index(request):
    dict_jinja = {'home':True,'login':False}
    if(request.user.is_authenticated):
        dict_jinja['logged_in']= True
    else:
        pass
    return render(request,'home/index.html',dict_jinja)

class indexView(TemplateView):
    template_name = "home/index.html"

def about(request):
    pass

home/templates/home/includes/base1.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="GroWithMe">
    <meta name="author" content="Soyuz Jung Basnet">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css'%}"/>
      {% block content1 %}{% endblock content1 %}
    <link rel="shortcut icon" sizes="32x32" type="image/png" href="{% static '/home/images/logo-small.png' %}"/>
    <title> {% block head_title %}{% endblock %} | GroWithMe</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

  </head>
  <body>
    {% block body %}
    {% endblock %}
    {% load staticfiles %}
    <script src="{% static 'home/javascript/meny.js' %}"></script>
    <script>
			// Create an instance of Meny
			var meny = Meny.create({
				// The element that will be animated in from off screen
				menuElement: document.querySelector( '.meny' ),

				// The contents that gets pushed aside while Meny is active
				contentsElement: document.querySelector( '.contents' ),

				// [optional] The alignment of the menu (top/right/bottom/left)
				position: Meny.getQuery().p || 'left',

				// [optional] The height of the menu (when using top/bottom position)
				height: 200,

				// [optional] The width of the menu (when using left/right position)
				width: 260,

				// [optional] Distance from mouse (in pixels) when menu should open
				threshold: 40,

				// [optional] Use mouse movement to automatically open/close
				mouse: true,

				// [optional] Use touch swipe events to open/close
				touch: true
			});

			// API Methods:
			// meny.open();
			// meny.close();
			// meny.isOpen();

			// Events:
			// meny.addEventListener( 'open', function(){ console.log( 'open' ); } );
			// meny.addEventListener( 'close', function(){ console.log( 'close' ); } );

			// Embed an iframe if a URL is passed in
			if( Meny.getQuery().u && Meny.getQuery().u.match( /^http/gi ) ) {
				var contents = document.querySelector( '.contents' );
				contents.style.padding = '0px';
				contents.innerHTML = '<div class="cover"></div><iframe src="'+ Meny.getQuery().u +'" style="width: 100%; height: 100%; border: 0; position: absolute;"></iframe>';
			}
		</script>
  {% block additional %}
  {% endblock additional %}
  </body>
</html>

home/templates/home/includes/navbar.html
{% block content %}
    {% include 'home/includes/svg-def.html' %}
    <div class="meny">
            <div class="logo_div_nav">
                    {% load staticfiles %}<img class="logo_nav" src="{% static 'home/images/logo-small.png' %}"/>
                    <h1 class="logo_text_nav">GroWithMe</h1>
            </div>

			<h2 class="navbar_header">Menu</h2>
            {% if explore %}
                <ul class="navbar_ul">
                    <li>
                        <form method="get" action="{%  url 'forum:search'%}" class="e_search_group" autocomplete="off">
                                    <div class="input-group">
                                        <input type="text" class="input-group input-group-text e_search_input" name="keyword"placeholder="Search"/>
                                        <button class="btn btn-lg btn-success e_search_button" type="submit">
                                            <svg class="icon icon-search"><use xlink:href="#icon-search"></use></svg>
                                        </button>
                                    </div>
                        </form>
                    </li>
                </ul>
            {% endif %}
			<ul class="navbar_ul">
                 <a href="{% url 'home:index' %}" class="navbar_li_a">
                    <li class="navbar_li {% if home %}selected{% endif %}">
                        <svg class="icon icon-home" ><use xlink:href="#icon-home"></use></svg>
                            <span class="navbar_li_text">&nbsp;Home</span>
                    </li>
                 </a>

                <a href="{% url 'forum:index'%}" class="navbar_li_a">
				<li class="navbar_li {% if forum %}selected{% endif %}">
                    <svg class="icon icon-users"><use xlink:href="#icon-users"></use></svg>
                    <span class="navbar_li_text">&nbsp;Forum</span>
                </li>
                </a>

                <a href="{% url 'minefield:index' %}" class="navbar_li_a">
                    <li class="navbar_li {% if about %}selected{% endif %}">
                            {% load staticfiles %}<img src="{% static 'forum/images/minefield_nav.svg' %}" class="minefield_logo_nav" style="width:25px;height:25px;color:white"/>
                            <span class="navbar_li_text">&nbsp;MineField</span>
                    </li>
                </a>

                {% if not logged_in %}
                    <a href="{% url 'accounts:login'%}" class="navbar_li_a">
                        <li class="navbar_li {% if login %}selected{% endif %}">
                        <svg class="icon icon-key"><use xlink:href="#icon-key"></use></svg>
                        <span class="navbar_li_text">&nbsp;Login</span>
                        </li>
                    </a>
                {% else %}
                    <a href="{% url 'accounts:logout'%}" class="navbar_li_a">
                        <li class="navbar_li {% if login %}selected{% endif %}">
                            <svg class="icon icon-exit"><use xlink:href="#icon-exit"></use></svg>
                                <span class="navbar_li_text">&nbsp;Logout</span>
                        </li>
                    </a>
                {% endif %}
                <a href="{% url 'accounts:register' %}" class="navbar_li_a">
                    {% if not logged_in %}<li class="navbar_li {% if register %}selected{% endif %}">
                            <svg class="icon icon-clipboard"><use xlink:href="#icon-clipboard"></use></svg>
                            <span class="navbar_li_text">&nbsp;Sign Up</span>
                    </li>
                    {% endif %}
                </a>
                <a href="{% url 'home:about' %}" class="navbar_li_a">
                    <li class="navbar_li {% if about %}selected{% endif %}">
                            <svg class="icon icon-info"><use xlink:href="#icon-info"></use></svg>
                            <span class="navbar_li_text">&nbsp;About</span>
                    </li>
                </a>
			</ul>
    </div>

    <div class="meny-arrow"></div>
{% endblock %}

home/templates/home/includes/svg-def.html
{% block content %}
<svg style="position: absolute; width: 0; height: 0; overflow: hidden" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <defs>
            <symbol id="icon-home" viewBox="0 0 32 32">
                <title>home</title>
                <path d="M32 18.451l-16-12.42-16 12.42v-5.064l16-12.42 16 12.42zM28 18v12h-8v-8h-8v8h-8v-12l12-9z"></path>
            </symbol>
            <symbol id="icon-key" viewBox="0 0 32 32">
                <title>key</title>
                <path d="M22 0c-5.523 0-10 4.477-10 10 0 0.626 0.058 1.238 0.168 1.832l-12.168 12.168v6c0 1.105 0.895 2 2 2h2v-2h4v-4h4v-4h4l2.595-2.595c1.063 0.385 2.209 0.595 3.405 0.595 5.523 0 10-4.477 10-10s-4.477-10-10-10zM24.996 10.004c-1.657 0-3-1.343-3-3s1.343-3 3-3 3 1.343 3 3-1.343 3-3 3z"></path>
            </symbol>
            <symbol id="icon-info" viewBox="0 0 32 32">
                <title>info</title>
                <path d="M14 9.5c0-0.825 0.675-1.5 1.5-1.5h1c0.825 0 1.5 0.675 1.5 1.5v1c0 0.825-0.675 1.5-1.5 1.5h-1c-0.825 0-1.5-0.675-1.5-1.5v-1z"></path>
                <path d="M20 24h-8v-2h2v-6h-2v-2h6v8h2z"></path>
                <path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13z"></path>
            </symbol>
            <symbol id="icon-exit" viewBox="0 0 32 32">
                <title>exit</title>
                <path d="M24 20v-4h-10v-4h10v-4l6 6zM22 18v8h-10v6l-12-6v-26h22v10h-2v-8h-16l8 4v18h8v-6z"></path>
            </symbol>
            <symbol id="icon-clipboard" viewBox="0 0 32 32">
                <title>clipboard</title>
                <path d="M29 4h-9c0-2.209-1.791-4-4-4s-4 1.791-4 4h-9c-0.552 0-1 0.448-1 1v26c0 0.552 0.448 1 1 1h26c0.552 0 1-0.448 1-1v-26c0-0.552-0.448-1-1-1zM16 2c1.105 0 2 0.895 2 2s-0.895 2-2 2c-1.105 0-2-0.895-2-2s0.895-2 2-2zM28 30h-24v-24h4v3c0 0.552 0.448 1 1 1h14c0.552 0 1-0.448 1-1v-3h4v24z"></path>
                <path d="M14 26.828l-6.414-7.414 1.828-1.828 4.586 3.586 8.586-7.586 1.829 1.828z"></path>
            </symbol>
            <symbol id="icon-users" viewBox="0 0 36 32">
                <title>users</title>
                <path d="M24 24.082v-1.649c2.203-1.241 4-4.337 4-7.432 0-4.971 0-9-6-9s-6 4.029-6 9c0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h28c0-4.030-5.216-7.364-12-7.918z"></path>
                <path d="M10.225 24.854c1.728-1.13 3.877-1.989 6.243-2.513-0.47-0.556-0.897-1.176-1.265-1.844-0.95-1.726-1.453-3.627-1.453-5.497 0-2.689 0-5.228 0.956-7.305 0.928-2.016 2.598-3.265 4.976-3.734-0.529-2.39-1.936-3.961-5.682-3.961-6 0-6 4.029-6 9 0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h8.719c0.454-0.403 0.956-0.787 1.506-1.146z"></path>
            </symbol>
            <symbol id="icon-notification" viewBox="0 0 32 32">
                <title>notification</title>
                <path d="M16 3c-3.472 0-6.737 1.352-9.192 3.808s-3.808 5.72-3.808 9.192c0 3.472 1.352 6.737 3.808 9.192s5.72 3.808 9.192 3.808c3.472 0 6.737-1.352 9.192-3.808s3.808-5.72 3.808-9.192c0-3.472-1.352-6.737-3.808-9.192s-5.72-3.808-9.192-3.808zM16 0v0c8.837 0 16 7.163 16 16s-7.163 16-16 16c-8.837 0-16-7.163-16-16s7.163-16 16-16zM14 22h4v4h-4zM14 6h4v12h-4z"></path>
            </symbol>
            <symbol id="icon-user" viewBox="0 0 32 32">
                <title>user</title>
                <path d="M18 22.082v-1.649c2.203-1.241 4-4.337 4-7.432 0-4.971 0-9-6-9s-6 4.029-6 9c0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h28c0-4.030-5.216-7.364-12-7.918z"></path>
            </symbol>
            <symbol id="icon-lock" viewBox="0 0 32 32">
                <title>lock</title>
                <path d="M18.5 14h-0.5v-6c0-3.308-2.692-6-6-6h-4c-3.308 0-6 2.692-6 6v6h-0.5c-0.825 0-1.5 0.675-1.5 1.5v15c0 0.825 0.675 1.5 1.5 1.5h17c0.825 0 1.5-0.675 1.5-1.5v-15c0-0.825-0.675-1.5-1.5-1.5zM6 8c0-1.103 0.897-2 2-2h4c1.103 0 2 0.897 2 2v6h-8v-6z"></path>
            </symbol>
            <symbol id="icon-checkmark" viewBox="0 0 32 32">
                <title>checkmark</title>
                <path d="M27 4l-15 15-7-7-5 5 12 12 20-20z"></path>
            </symbol>
            <symbol id="icon-mail3" viewBox="0 0 32 32">
                <title>mail3</title>
                <path d="M26.667 0h-21.333c-2.934 0-5.334 2.4-5.334 5.334v21.332c0 2.936 2.4 5.334 5.334 5.334h21.333c2.934 0 5.333-2.398 5.333-5.334v-21.332c0-2.934-2.399-5.334-5.333-5.334zM5.707 27.707l-2.414-2.414 8-8 0.914 0.914-6.5 9.5zM4.793 6.207l0.914-0.914 10.293 8.293 10.293-8.293 0.914 0.914-11.207 13.207-11.207-13.207zM26.293 27.707l-6.5-9.5 0.914-0.914 8 8-2.414 2.414z"></path>
            </symbol>
            <symbol id="icon-search" viewBox="0 0 32 32">
                <title>search</title>
                <path d="M31.008 27.231l-7.58-6.447c-0.784-0.705-1.622-1.029-2.299-0.998 1.789-2.096 2.87-4.815 2.87-7.787 0-6.627-5.373-12-12-12s-12 5.373-12 12 5.373 12 12 12c2.972 0 5.691-1.081 7.787-2.87-0.031 0.677 0.293 1.515 0.998 2.299l6.447 7.58c1.104 1.226 2.907 1.33 4.007 0.23s0.997-2.903-0.23-4.007zM12 20c-4.418 0-8-3.582-8-8s3.582-8 8-8 8 3.582 8 8-3.582 8-8 8z"></path>
            </symbol>
            <symbol id="icon-binoculars" viewBox="0 0 32 32">
                <title>binoculars</title>
                <path d="M2 0h12v2h-12zM18 0h12v2h-12zM29.75 10h-1.75v-8h-8v8h-8v-8h-8v8h-1.75c-1.238 0-2.25 1.012-2.25 2.25v17.5c0 1.238 1.012 2.25 2.25 2.25h9.5c1.238 0 2.25-1.012 2.25-2.25v-11.75h4v11.75c0 1.238 1.012 2.25 2.25 2.25h9.5c1.238 0 2.25-1.012 2.25-2.25v-17.5c0-1.238-1.012-2.25-2.25-2.25zM10.875 30h-7.75c-0.619 0-1.125-0.45-1.125-1s0.506-1 1.125-1h7.75c0.619 0 1.125 0.45 1.125 1s-0.506 1-1.125 1zM17 16h-2c-0.55 0-1-0.45-1-1s0.45-1 1-1h2c0.55 0 1 0.45 1 1s-0.45 1-1 1zM28.875 30h-7.75c-0.619 0-1.125-0.45-1.125-1s0.506-1 1.125-1h7.75c0.619 0 1.125 0.45 1.125 1s-0.506 1-1.125 1z"></path>
            </symbol>
            <symbol id="icon-circle-left" viewBox="0 0 32 32">
                <title>circle-left</title>
                <path d="M16 32c8.837 0 16-7.163 16-16s-7.163-16-16-16-16 7.163-16 16 7.163 16 16 16zM16 3c7.18 0 13 5.82 13 13s-5.82 13-13 13-13-5.82-13-13 5.82-13 13-13z"></path>
                <path d="M20.914 9.914l-2.829-2.829-8.914 8.914 8.914 8.914 2.828-2.828-6.086-6.086z"></path>
            </symbol>
            <symbol id="icon-plus" viewBox="0 0 32 32">
                <title>plus</title>
                <path d="M31 12h-11v-11c0-0.552-0.448-1-1-1h-6c-0.552 0-1 0.448-1 1v11h-11c-0.552 0-1 0.448-1 1v6c0 0.552 0.448 1 1 1h11v11c0 0.552 0.448 1 1 1h6c0.552 0 1-0.448 1-1v-11h11c0.552 0 1-0.448 1-1v-6c0-0.552-0.448-1-1-1z"></path>
            </symbol>
            <symbol id="icon-cancel-circle" viewBox="0 0 32 32">
                <title>cancel-circle</title>
                <path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13z"></path>
                <path d="M21 8l-5 5-5-5-3 3 5 5-5 5 3 3 5-5 5 5 3-3-5-5 5-5z"></path>
                </symbol>
            <symbol id="icon-quill" viewBox="0 0 32 32">
                <title>quill</title>
                <path d="M0 32c4-12 14.469-32 32-32-8.219 6.594-12 22-18 22s-6 0-6 0l-6 10h-2z"></path>
                </symbol>
        </defs>
</svg>
{% endblock %}